[package]
name = "lIIl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.19", features = ["derive"] }
once_cell = "1.18.0"
pest = "2.7.1"
pest_derive = "2.7.1"
rand = "0.8.5"
