name: Tests

on:
  push:
    branches:
      - main
    paths:
      - "**.rs"
      - "**.lIIl"
  pull_request:
    branches:
      - main
    paths:
      - "**.rs"
      - "**.lIIl"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
            components: rustfmt, clippy
      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
